name: Latest youtube
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: andrewstech/blog-post-workflow@master
        with:
          max_post_count: "7"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCc6HVnjG3CD7hkk4Hmg1Lnw"
